repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.9
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.6
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        name: mypy --strict
        args:
          - --strict
          - src/tg_feedback_bot_ru
        pass_filenames: false
        additional_dependencies:
          - pytest>=9.0.1
          - pytest-asyncio>=1.3.0
          - pytest-cov>=7.0.0
          - pydantic>=2.12.4
          - pydantic-settings>=2.12.0
          - sqlalchemy[postgresql_asyncpg]>=2.0.44
          - aiotgbot[sqlalchemy]>=0.18.3
          - aiorunner>=0.2.5
          - aiojobs>=1.4.0
          - uvloop>=0.22.1
          - msgspec>=0.19.0
          - more-itertools>=10.8.0

  - repo: https://github.com/DetachHead/basedpyright-prek-mirror
    rev: 1.33.0
    hooks:
      - id: basedpyright
        pass_filenames: false
